name: Trigger auto deployment for container-app-smtgv56kvjsee

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'vote/**'
    - '.github/workflows/container-app-smtgv56kvjsee-AutoDeployTrigger-72219082-ddba-4fdc-9d45-cff466a7720e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSMTGV56KVJSEE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSMTGV56KVJSEE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSMTGV56KVJSEE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/vote 
          registryUrl: containerregistrysmtgv56kvjsee.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPSMTGV56KVJSEE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSMTGV56KVJSEE_REGISTRY_PASSWORD }}
          containerAppName: container-app-smtgv56kvjsee
          resourceGroup: examplevotingapp8bd8
          imageToBuild: containerregistrysmtgv56kvjsee.azurecr.io/container-app-smtgv56kvjsee:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


