name: Trigger auto deployment for container-app-shcgh6ympbtrw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'vote/**'
    - '.github/workflows/container-app-shcgh6ympbtrw-AutoDeployTrigger-34738490-7f11-4875-8658-1eb9476bf0e7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSHCGH6YMPBTRW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSHCGH6YMPBTRW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSHCGH6YMPBTRW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/vote 
          registryUrl: containerregistryshcgh6ympbtrw.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPSHCGH6YMPBTRW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSHCGH6YMPBTRW_REGISTRY_PASSWORD }}
          containerAppName: container-app-shcgh6ympbtrw
          resourceGroup: examplevotingapp9d95
          imageToBuild: containerregistryshcgh6ympbtrw.azurecr.io/container-app-shcgh6ympbtrw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


