name: Trigger auto deployment for container-app-nygxus3ps7oz2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'vote/**'
    - '.github/workflows/container-app-nygxus3ps7oz2-AutoDeployTrigger-30d925d3-2102-44fc-9f9a-ca40c9e52c32.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNYGXUS3PS7OZ2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNYGXUS3PS7OZ2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNYGXUS3PS7OZ2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/vote 
          registryUrl: containerregistrynygxus3ps7oz2.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPNYGXUS3PS7OZ2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNYGXUS3PS7OZ2_REGISTRY_PASSWORD }}
          containerAppName: container-app-nygxus3ps7oz2
          resourceGroup: examplevotingappb9c5
          imageToBuild: containerregistrynygxus3ps7oz2.azurecr.io/container-app-nygxus3ps7oz2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


